### ISSUE TITLE
Cannot obtain the script output/result from the script_exporter probe

### ISSUE THREAD

**Issue by massano-davide** [ricoberger/script_exporter#83] opened 2023-08-21 15:05 UTC
Looking at the probe page of my custom script execution, and following of course the readme examples, there's no way to obtain the script stdout result.
In an example script, that returns only and always the value "50" looking at probe values it returns only

```
# HELP script_success Script exit status (0 = error, 1 = success).
# TYPE script_success gauge
script_success{script="pint01"} 0
# HELP script_duration_seconds Script execution time, in seconds.
# TYPE script_duration_seconds gauge
script_duration_seconds{script="pint01"} 0.005414
# HELP script_exit_code The exit code of the script.
# TYPE script_exit_code gauge
script_exit_code{script="pint01"} 0
```

without any trace of the output.
In the readme file, it's only explained how to ignore the output on the prometheus.yaml, not how to force it.
What am I missing? :(

**Comment by ironstas1k** [comment] 2023-09-21 14:04
I can confirm that it's working for me the same way, even with config from examples.

**Comment by ricoberger** [comment] 2023-10-13 08:44
I will close the issue for now, because of missing feedback.

If you still have an issue please let me know and I can re-open the issue.

**Closed by ricoberger** 2023-10-13 08:44 UTC
Labels: bug
